# GruvboxMaterialDarkHard
[colors]
foreground = "#d4be98"
background = "#1d2021"
cursor_bg = "#d4be98"
cursor_border = "#d4be98"
cursor_fg = "#1d2021"
selection_bg = "#d4be98" 
selection_fg = "#3c3836"

ansi = []
brights = []
