#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

# Workspaces
bspc monitor eDP1 -d 1 2 3 4 5

bspc config border_width         4
bspc config window_gap          20

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


wal -i $HOME/wallpapers/wallpaper.png
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
$HOME/.config/polybar/launch.sh
